### PR TITLE
Update provincial cumulative data 2 June 2020

### PR DESCRIPTION
**Pull request by chadwpetersen**
This updates the following provincial data:

- Confirmed
- Deaths
- Recoveries

### CODE REVIEW

**Comment by vukosim** [comment]
Hey @chadwpetersen could you also adopt and update the provincial testing csv?

It could be automated as well.

**Comment by chadwpetersen** [comment]
@vukosim -yes sure I can adopt the provincial testing data as well.

**Comment by chadwpetersen** [comment]
@vukosim is the Go scraper still being used to automate provincial data? I could add some changes to that if it is still actively being used?

**Comment by vukosim** [comment]
@chadwpetersen unfortunately no. It was used for the earlier minister statements. If the minister keeps the current statements consistent, we could automate so that you don't need to enter things manually to the 4 files.

**Comment by chadwpetersen** [comment]
@vukosim I have built a tool that downloads all the tables from media releases. I can try and clean it up a bit and contribute it to this repo if you would like? So it at least is semi-automatic.

**Comment by vukosim** [comment]
Go for it.

**Pull request merged**
