### PR TITLE
get last modified from git commit

### PR DESCRIPTION
**Pull request by Remwrath**
this is more for review as I would ideally like to update all compatible api's if this solution is acceptable.
Related to #207

### CODE REVIEW

**Comment by vukosim** [comment]
@Vutlhari

**Comment by Vutlhari** [comment]
@Remwrath I think @bmerry had some thoughts about this issue.

**Comment by bmerry** [comment]
I don't think this will work. It's assuming that it's being run from within a Git checkout, but the Docker container has only the binary, and it fetches the CSV files from Github. Also since it's fetching the data from Github, the time the local checkout was modified won't necessarily match that on Github. I would say that an incorrect Last-Modified header is worse than none at all. One option would be to change the API to get the CSV files from the local directory, and add them into the Docker image. That also has the advantage of eliminating a round trip to Github to get the data, but does require the API to be redeployed every time the data changes.

If that is all done, it still only tells clients when the data last changed, but doesn't handle If-Last-Modified, so clients still have to fetch the data.

I'm planning to experiment with Varnish today. I'll update with what I learn.

**Comment by bmerry** [comment]
I've opened #240 to add Varnish. It looks like I'd slightly misunderstood how Last-Modified/ETag/If-Modified-Since/If-None-Match work: they're for revalidating cached content when cached content is considered stale.

Whether this PR is worth investigating further probably depends on what the goal is:
1. If it's to know (through an API) when the data was last changed then fair enough - although I'm struggling to think of a use case that isn't just about efficiency/caching.
2. If it's to improve efficiency, I think it'll be difficult to make much improvement over #240 given that the data sets are tiny in modern terms (particularly after the gzip compression) - doing all the HTTP header parsing and comparison logic could easily take just as long as transferring the extra few KB.

**Pull request closed without merging**
