### PR TITLE
Feature/automated-ministry-release-scraping

### PR DESCRIPTION
**Pull request by cishiv**
WiP.
https://gov.za is currently down so I am unable to test/move forward for the moment.

### CODE REVIEW

**Comment by cishiv** [comment]
Currently a work in progress.

**Comment by cishiv** [comment]
Blocked on this for the evening, Will probably pick it up tomorrow evening...

**Comment by vukosim** [comment]
Could you add a README and also requirements to run.

**Comment by cishiv** [comment]
Hey @vukosim , will do as soon as I get some available time. Currently just going through a work-from-home transition at the moment. I do not want to merge this as yet and will add you as a reviewer as soon as I do.
TODO:
1. README
2. Requirements to run

**Comment by cishiv** [comment]
Right, i've pushed a change adding a stub for a readme as well as getting the tool to work using `http://www.nicd.ac.za/` instead of `gov.za`; I will probaly finish this up tomorrow.
Where we are at right now:
```
shiv@LAPTOP-ENNNEGDS:~/dev/projects/covid19za/scraper$ ./scraper
FETCHING DOCUMENT
CRAWLING
Crawling options (Please note that updates before the 16th of March may be unable to be parsed due to formatting inconsistencies)
1 http://www.nicd.ac.za/covid-19-update-18/
2 http://www.nicd.ac.za/covid-19-update-17/
3 http://www.nicd.ac.za/covid-19-update-16/
4 http://www.nicd.ac.za/covid-19-update-15/
5 http://www.nicd.ac.za/covid-19-update-14/
Please select an option to crawl 1 - 5
1
NAVIGATING TO http://www.nicd.ac.za/covid-19-update-18/
FETCHING DOCUMENT
PARSING http://www.nicd.ac.za/covid-19-update-18/
63,16-03-2020,20200316,South Africa,GP,ZA-GP,33,male,Travelled to Spain
64,16-03-2020,20200316,South Africa,GP,ZA-GP,68,year-old-female,Travelled to Austria
65,16-03-2020,20200316,South Africa,GP,ZA-GP,30,male,Travelled to India
66,16-03-2020,20200316,South Africa,GP,ZA-GP,39,male,Travelled to the United States of America
67,16-03-2020,20200316,South Africa,GP,ZA-GP,43,female,Travelled to the United States of America
68,16-03-2020,20200316,South Africa,GP,ZA-GP,50,male,Travelled to France and the United Kingdom
69,16-03-2020,20200316,South Africa,GP,ZA-GP,37,not specified,Travelled to the United States of America, Dubai and Mexico
70,16-03-2020,20200316,South Africa,WC,ZA-WC,39,male,Travelled to Canada
71,16-03-2020,20200316,South Africa,WC,ZA-WC,15,male,Travelled to France
72,16-03-2020,20200316,South Africa,LIM,ZA-LIM,29,male,Travelled to France and the Netherlands
73,16-03-2020,20200316,South Africa,MP,ZA-MP,55,male,Travelled to France
```

**Comment by vukosim** [comment]
Hey @cishiv Seems sacoronavirus.co.za might also be the most freshest for now.

**Comment by cishiv** [comment]
@vukosim will take a look at sacoronavirus.co.za after work today. 
Thanks for merging.

**Pull request merged**
