### PR TITLE
Update provincial_wc_cumulative.csv

### PR DESCRIPTION
**Pull request by aidanhorn**
The missing data on weekends was assumed to have no change by Shaun, but I think it would be better to impute a linear change. I add a third of the difference between Friday and Monday, to get Saturday, and two thirds of the difference for Sunday, and I round off the values to the nearest integer. If you are happy with this, we should mention it in the readme.md file.

### CODE REVIEW

**Comment by dmackie** [comment]
@aidanhorn I disagree.  And I believe it has been stated before that this dataset should only publish the numbers officially reported. Any interpretations of the data are left up to the user of the data.

**Comment by aidanhorn** [comment]
> 
> 
> @aidanhorn I disagree. And I believe it has been stated before that this dataset should only publish the numbers officially reported. Any interpretations of the data are left up to the user of the data.

In pull request #689, I showed that I wanted to leave the weekends blank. [Shaun Garnett then filled in a weekend with no increases in the numbers.](https://github.com/dsfsi/covid19za/commit/27e75c664b5a6b5eef6d13d67dee291f4ec39e6c#r42377968)

**Comment by vukosim** [comment]
@aidanhorn I think we should leave them blank if there were no updates. Is there a consensus?

**Comment by dmackie** [comment]
This is what happens when we have a missing source field, as you cannot put a number in without a source and without a source, my feelings are they should be blank.

**Comment by aidanhorn** [comment]
Yes, it is fine to leave them blank.

**Comment by dmackie** [comment]
Does blank mean there is no line for that date
OR
There is a line for that date but no values

**Comment by aidanhorn** [comment]
I think it is better to put the date in, but leave the cases numbers out. Because, users (like me) may be taking the lagged difference.

**Comment by dmackie** [comment]
Idea: When we implement adding source fields (which is something I am still wanting to do) we maybe should add a source of "No data for this date"

**Pull request merged**
