### PR TITLE
Western Cape District Information

### PR DESCRIPTION
**Pull request by nikrich**
I've structured it in a non-cumulative manner because managing the data in that way, with more districts showing cases, will be unmanageable.

### CODE REVIEW

**Comment by webdevan** [comment]
What about putting the date in the file name so we can also track the change over time? Assuming these numbers are published each day.

**Comment by nikrich** [comment]
Added date to match international data layout. The reason for this is, more districts and sub-districts will most likely get added as cases build up.

**Comment by vukosim** [comment]
Hey @nikrich we could create sub-folder in the data folder. Then we follow a similar format to the cumulative province, but now it will be for WC.

**Comment by nikrich** [comment]
Sure thing! Do you mean data/district_data/wc ? And then drop the wc data in there for district and sub-districts?

**Comment by vukosim** [comment]
more like 

district_data/provincial_wc_cumulative.csv

**Comment by nikrich** [comment]
Updated, @vukosim see if that's better please? :)

**Comment by vukosim** [comment]
Is it possibel to create a key file with abbreviations of all the districts, and then have each day count only being a single row?

**Comment by nikrich** [comment]
Sure thing!

**Comment by nikrich** [comment]
Done, please review @vukosim

**Comment by vukosim** [comment]
New numbers https://www.gov.za/speeches/premier-alan-winde-fight-against-coronavirus-covid-19-31-mar-2020-0000

**Comment by nikrich** [comment]
On it!

**Pull request merged**
