### PR TITLE
Update the cumulative provincial data for 2 June 2020

### PR DESCRIPTION
**Pull request by chadwpetersen**
Part 2 -the data has been updated again

Contains the following cumulative provincial data:

- Confirmed
- Deaths
- Recoveries

### CODE REVIEW

**Comment by chadwpetersen** [comment]
This also includes an update for the testing timeline data.

**Comment by lrossouw** [comment]
This looks ok.  Why was there an update earlier today (2 June) containing the same data as yesterday?

**Comment by lrossouw** [comment]
I see now the cases changed but deaths stayed the same.

**Comment by chadwpetersen** [comment]
@lrossouw on top of that yesterday and today the NICD released data multiple times throughout the course of the day as well.

**Comment by lrossouw** [comment]
Ai it's confusing from their side.  Perhaps we should only update the figures that change?  I guess they also deleted their tweet corresponding to the earlier release as I can't find it now.

**Comment by chadwpetersen** [comment]
Yes they delete their tweets when they post with data that has errors in it. Hmm.. as for updating figures that change only -I think that could be tricker given the current structure. Do you mean that the column values should be set to null when no changes occur to a column? If so -that would mean that people who use this file would have to traverse up a column to find the correct data for the current data which might make it a bit tricker to use these files.

**Comment by lrossouw** [comment]
I am not sure.  I was thinking that the all the deaths didn't change, so simply leave the 2 June data out, but perhaps it's better to capture as they tweet and leave the sense check for whatever logic uses the data.

**Comment by chadwpetersen** [comment]
Ah -I see what you mean. So if there is no changes for the day, for a given data file then do not update it? That is possible, so only add a new line to the `csv` if at least 1 of the data points has been modified. But again, not too sure if others in the community using these files are expecting daily changes or not.

This change will also introduce a bit of ambiguity as well as it could either mean that no one captured for the day or no new data exists. Then the only way to know for sure which one it is, would be to look up some data sources. So maybe daily captures helps out with that at least?

**Comment by lrossouw** [comment]
Ja, but on second thought I think it may be better to capture as is, and delete if they delete.  The logic in the process that uses the data can then determine what's valid (or not).

**Comment by chadwpetersen** [comment]
@vukosim can we get this merged in?

**Comment by vukosim** [comment]
Thanks. I was also fixing, thanks.

**Comment by chadwpetersen** [comment]
Ah -no problemo :). Thanks a lot :)

**Pull request merged**
