### PR TITLE
feat(README): includes coronamap in visualisations

### PR DESCRIPTION
**Pull request by JayWelsh**
Screenshot 2020-03-20 at 20 13 03

### CODE REVIEW

**Comment by vukosim** [comment]
Is it possible to make it a choropleth map? Second also option for light and dark theme would be good.

**Comment by JayWelsh** [comment]
@vukosim I will take a look into the complexity of making it a choropleth map using this charting library, in the meantime, I'm working on implementing a few graphs.

P.S. A dark / light theme option for the map has been deployed within the last few minutes and can be toggled using the button in the top right corner 🌈

**Comment by JayWelsh** [comment]
@vukosim Choropleth map can now be toggled on and off by clicking the button under the dark / light mode switch 🌈

**Comment by vukosim** [comment]
Great, can we make sure the map references this repo for data.

**Comment by JayWelsh** [comment]
@vukosim as things stand, the map attribution data is in the bottom right of the screen and contains attributions to all parties involved in the map, including attribution of data to https://dsfsi.github.io/ (would you prefer for that link to direct to this GitHub repo instead?). GitHub repo gives attribution as well: https://github.com/JayWelsh/coronamap

Is that alright? 🌠

**Comment by vukosim** [comment]
Yes, direct link to this repo would be best. I will merge this.

**Comment by JayWelsh** [comment]
Thanks a lot @vukosim, I will adjust the URL. 🌅

**Pull request merged**
