### PR TITLE
Update Realtime R0 notebook with latest k-sys methods

### PR DESCRIPTION
**Pull request by heerden**
Hello Vukosi and Team

Your project is amazing! Hope to add a bit of value. I have a background in control engineering and have done some calculations with Notebooks before.

Before I came across your repo, I was already modifying the Realtime R0 notebook: https://github.com/heerden/covid-19/tree/master_za

I got data from another API but it was limited to only country level data. Keeping track of notebook diff changes is hard, so I followed this process to have a ZA notebook, but with up to date methods from the master notebook.

1. Create a new notebook (Realtime_RO_World) and "run" the master notebook inside, that the main methods are exposed
2. Import the DSFSI data
3. Modify data that they can work with master methods
4. Only create essential cells that create plot and do not recreate any methods

To make the merge back to your repo possible, I followed steps 2 and 3 on the master notebook, which is in this pull request. In this way all the info and explanatory text is still in order.

The results from this notebook matches my notebook, from heerden/covid-19/tree/master_za/Realtime_RO_World. Thus I am confined in the results.

Your final verification will be appreciated! I can keep tracking the k-sys repo and repeat this process, if there is not any other suggestions.

### CODE REVIEW

**Comment by vukosim** [comment]
Thank you. Will review.

**Comment by riazarbi** [comment]
@heerden I'm currently refitting the MCMC notebook from k-sys to try derive Rt for the City of Cape Town for internal planning use. Any reason you used the realtime_R0 notebook rather than the MCMC version?

I'm not much of a bayesian, so if I'm committing an error by using the MCMC version rather than the realtime_R0 one please do let me know.

**Comment by heerden** [comment]
@riazarbi That group's MCMC notebook is still very new, thus I continue to work with the R0 notebook. Not dogmatic about any approach.

The epiforecasts did a good job to execute that modelling, but their model is not updated in real time. I would rather use python, than their R models. So that is my only bias.

I will be building an online dashboard next, to compute this model in realtime, as I understand this is an issue. Might take another week. Planning to use a mixture of Django and plotly, to store and display the calculated data.

Good luck with the CPT model.

**Comment by vukosim** [comment]
@heerden and @riazarbi one thing we could do is build a github action that runs every 24 hours that calculates the Rt for all provinces and dumps the csv file. Then people can read that. We can have one for Bayesian and one for MCMC

Thoughts?

**Comment by riazarbi** [comment]
I can submit a pull request with my MCMC one if someone is willing to code
review it for statistical correctness.

**Comment by heerden** [comment]
@vukosim Automating the run on Github is a clever trick and the fastest approach. Have we defined any yml in the project thus far? I cannot see any yet.

We could follow this script https://github.com/marketplace/actions/run-notebook, if you do not have a template already?

**Pull request merged**
