### PR TITLE
Caching for API

### PR DESCRIPTION
**Pull request by bmerry**
This makes two changes:

1. Add Cache-control header to all responses, specifying caching for 2 minutes. Clients that do their own caching (particularly browsers) will then reuse the response, even if a Javascript app is polling more often.
2. Add Varnish in front of the application. Varnish will cache responses for 2 minutes and serve them to all clients that aren't doing their own caching. This will still put a little load on the web dyno, but much less than before because it just needs to dump the cached response on the wire rather than fetching CSV from Github and transforming it into JSON.

@Remwrath @Vutlhari this is probably of interest to you.

### CODE REVIEW

**Comment by bmerry** [comment]
@Vutlhari did this deploy successfully on Heroku? I'm not seeing the Varnish headers when I query the API.

**Comment by Vutlhari** [comment]
> @Vutlhari did this deploy successfully on Heroku? I'm not seeing the Varnish headers when I query the API.

The deployment only happens when I push the latest changes to my fork (because I don't have access to this repo).

The latest changes have now been deployed.

**Comment by vukosim** [comment]
@Vutlhari Check your email you Have been added on team.

**Comment by Vutlhari** [comment]
> @Vutlhari Check your email you Have been added on team.

Didn't receive anything

**Comment by vukosim** [comment]
> > @Vutlhari Check your email you Have been added on team.
> 
> Didn't receive anything

Resent the invitation to GitHub team

**Pull request merged**
