### PR TITLE
Update wc cummulative

### PR DESCRIPTION
**Pull request by naturofix**
update wc_cummulative

### CODE REVIEW

**Comment by vukosim** [comment]
@naturofix please check conflicts or close.

**Comment by vukosim** [comment]
Thanks so much. Do shout if you need help.

**Review by naturofix — COMMENTED** [review]
I've made a pull request, with updates to the wc provincial data, please approve this pull request. 
Thanks

**Comment by vukosim** [comment]
Fixed @naturofix, there were conflicts that had not been resolved. I fixed them. Hope its fine now?

**Pull request merged**
