### PR TITLE
Created covid19za_timeline_summary_data.csv

### PR DESCRIPTION
**Pull request by SimonRosen173**
Condensed data for confirmed, tests, deaths and recoveries per day into one csv.
Also includes data for
- active cases per day
- confirmed, tests, deaths and recoveries per million population per day
- confirmed divided by tests per day
- deaths divided by confirmed per day
- recovered divided by confirmed per day

### CODE REVIEW

**Comment by dmackie** [comment]
Hi @SimonRosen173,  What are your plans for keeping this file updated as the other data files are updated?

**Comment by SimonRosen173** [comment]
I plan to update this data daily as I use this data for creating many of the graphs on the [Covid19 SA Data](https://covid19data.co.za/) site I maintain which I update daily. This data is already present and up to date in the repo of my site which you can view [here](https://github.com/SimonRosen173/Covid19SAData/blob/master/data/all_cum_data.csv). In general I update this data by midday the following day of when the data was released by government. 

I have used a date format inconsistent with the other csv files present in this repo but I will be able to amend that as well as adding a 'YYYYMMDD' column.

If needed I can also provide a python script that creates this csv file.

**Comment by vukosim** [comment]
Hey @SimonRosen173 Thank you for your work. I will interrogate this pull request later today and well have conversation.

**Comment by dmackie** [comment]
Hello,

I would be very interested in looking at possible using Github CI / Actions to auto update this file as other data files are merged into master.  A summary file is very useful but I personally would prefer there was a single source in the repo of each data type so there won't be duplication of work (and that's why I think it should be automated) and inconsistencies.

Thoughts?

-Dave

**Comment by SimonRosen173** [comment]
I do not have experience with GitHub Actions but I can provide a python script that gets the latest required data available in this repo and does all the necessary processing to update the data for this file automatically. 

Provided that the script is run after a successful merge it would load all the required data via loading from the url for where the raw representation of each csv file is hosted on this repo, i.e. for covid19za_timeline_testing.csv the url would be `https://raw.githubusercontent.com/dsfsi/covid19za/master/data/covid19za_timeline_testing.csv`. This is how I currently load all the data from this repo for my site, as well as for creating and updating this file. 

I however do not know how the output of this Python script would be used by GitHub Actions to update the 'covid19za_timeline_summary_data.csv' file, as well as what format the output should be in.

**Comment by vukosim** [comment]
@SimonRosen173 if you can write a jupyter notebook that does this, people can assist with creating a script for it. So can you add the notebook to his pull request.

**Comment by SimonRosen173** [comment]
Shall do. For now I am going to remove this file from my fork of the repo and close the pull request until I upload the Jupyter notebook. 

I have created a csv file for recovered per province so removing this summary file will allow me to add that as a separate pull request.

**Pull request closed without merging**
