### PR TITLE
Update provincial_gp_cumulative.csv for 18/07/2020 & 16/07/2020.

### PR DESCRIPTION
**Pull request by SimonRosen173**
1. Added data for 16-07-2020 & 18-07-2020 in provincial_gp_cumulative.csv.
    Data for 16-07-2020 was calculated using 'New Cases' fields in [twitter update for 17-07-2020](https://twitter.com/GautengHealth/status/1284490028232605696/photo/1).

 2. Data was converted from decimal to integer.

### CODE REVIEW

**Comment by shaze** [comment]
Simon, thanks I am maintaining these gp_* pages.

I have a master file with a script that  updates all the GP data so it doesn't really help to to have only one of the files updated.

Thanks for pointing out the issue of the floating point data. I'll fix the script and it will be corrected when I push the data tomorrow. Much appreciated

If you do have time would be great would be to maintain the provincial testing data. I see the file`data/covid19za_provincial_cumulative_timeline_testing.csv` directory has not been updated since the end of May. I did an update based on NICD documents to the version `district_data/provincial_testing_data.csv` based on NICD data. I have not pushed those through because there are two separate documents produced by NICD with what appears significantly discrepant data which needs to be understood. Let me know if you are prepared to take this on.

**Comment by SimonRosen173** [comment]
Ah, right my apologies.

If you are talking about the [weekly NICD testing summaries](https://www.nicd.ac.za/diseases-a-z-index/covid-19/surveillance-reports/) I have looked at that previously and I also noted that there are major inconsistencies between figures reported in each weekly testing summary. This coupled with the fact that the figures report the weekly increase and not the current total makes me wary that provincial testing data can be obtained from it accurately.  Unless there are sources that I am missing I believe only estimates of provincial testing figures and not true figures can be obtained.

**Comment by SimonRosen173** [comment]
@shaze I am considering working on some Python code that will use computer vision to obtain all the Gauteng Covid19 data from the GautengHealth Twitter updates. This code will also obtain deaths & recoveries figures. In a previous project I was moderately successful in doing this but the images I used were infographics with an inconsistent background. 

I am confident I will be much more successful using the GautengHealth twitter updates, which to the CV software should be very easy to read.

**Comment by shaze** [comment]
Simon thanks. Yes, if there is an automated procedure for collecting the data accurately that would be helpful. I am currently manually collecting -- it takes about 10 minutes a day but is a nuisance.  It may be better to work from the PDFs. I will write to the GDOH media person asking for that.

I'll also ask someone at the NICD for clarity on the testing figures. I see this as major missing data.

Thanks for pointing out inconsistencies. I will fix and push with today's figures

**Comment by SimonRosen173** [comment]
If I have access to the pdfs rather than just images, it should be a much simpler procedure to extract the data. 

Provided I have access to the pdfs I can create a Python module that will take the pdf as input and output the data for cases, recoveries and deaths by district & sub-district.

No problem. Thank you.

**Pull request closed without merging**
