### PR TITLE
added cumulative confirmed cases route

### PR DESCRIPTION
**Pull request by Steven-MKN**

### CODE REVIEW

**Comment by vukosim** [comment]
@Vutlhari can you help here.

**Comment by Vutlhari** [comment]
@Steven-MKN 

Can you please clarify what you are trying to add with this PR?

**Comment by Vutlhari** [comment]
@Steven-MKN  from what I see on you PR, I think you can just use the following endpoint to get the same data:

https://covid-za-api.herokuapp.com/cases/timeline/provincial/cumulative

Example response 

```
[ 
 {
    "date": "04-04-2020",
    "timestamp": "20200404",
    "provinces": {
      "eastern_cape": "25",
      "free_state": "85",
      "gauteng": "693",
      "kwazulu_natal": "232",
      "limpopo": "18",
      "mpumlanga": "18",
      "northern_cape": "7",
      "north_west": "11",
      "western_cape": "433",
      "unknown": "63"
    },
    "total": "1585"
  },
  {
    "date": "05-04-2020",
    "timestamp": "20200405",
    "provinces": {
      "eastern_cape": "31",
      "free_state": "87",
      "gauteng": "704",
      "kwazulu_natal": "246",
      "limpopo": "19",
      "mpumlanga": "18",
      "northern_cape": "8",
      "north_west": "11",
      "western_cape": "454",
      "unknown": "77"
    },
    "total": "1655"
  }
]
```

**Comment by Steven-MKN** [comment]
Thanks @Vutlhari

**Pull request closed without merging**
